#!/usr/bin/env node
/**
 * gen-abis.mjs
 * Reads forge build output and copies contract ABIs to packages/shared/src/abis/
 * Run: node scripts/gen-abis.mjs  (or via pnpm gen:abis)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const FORGE_OUT = join(ROOT, 'contracts/out');
const ABIS_OUT = join(ROOT, 'packages/shared/src/abis');

// Entries are either a contract name (artifact === export base name) or an
// { name, artifact } pair when the exported ABI comes from a differently-named artifact
// (e.g. ERC20Abi is the IERC20 interface ABI used for USDT interactions).
const CONTRACTS = [
  'ProjectFactory',
  'ProjectEscrow',
  'PositionNFT',
  { name: 'ERC20', artifact: 'IERC20' },
];

function extractAbi(artifactName) {
  const artifactPath = join(FORGE_OUT, `${artifactName}.sol`, `${artifactName}.json`);
  if (!existsSync(artifactPath)) {
    console.warn(`Warning: ${artifactPath} not found. Run 'forge build' first.`);
    return null;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  return artifact.abi;
}

function main() {
  mkdirSync(ABIS_OUT, { recursive: true });

  const exports = [];

  for (const entry of CONTRACTS) {
    const name = typeof entry === 'string' ? entry : entry.name;
    const artifact = typeof entry === 'string' ? entry : entry.artifact;
    const abi = extractAbi(artifact);
    if (!abi) continue;

    const filename = `${name}.abi.ts`;
    const content = `// Auto-generated by gen:abis — do not edit manually\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;

    writeFileSync(join(ABIS_OUT, filename), content);
    exports.push({ name, filename });
    console.log(`✓ Wrote ${name}.abi.ts`);
  }

  // Update index.ts
  const indexContent =
    exports
      .map(
        ({ name, filename }) =>
          `export { ${name}Abi } from './${filename.replace('.ts', '.js')}';`,
      )
      .join('\n') + '\n';

  writeFileSync(join(ABIS_OUT, 'index.ts'), indexContent);
  console.log(`✓ Updated abis/index.ts`);
}

main();
