#!/usr/bin/env node
/**
 * gen-abis.mjs
 * Reads forge build output and copies contract ABIs to packages/shared/src/abis/
 * Run: node scripts/gen-abis.mjs  (or via pnpm gen:abis)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const FORGE_OUT = join(ROOT, 'contracts/out');
const ABIS_OUT = join(ROOT, 'packages/shared/src/abis');

const CONTRACTS = [
  'ProjectFactory',
  'ProjectEscrow',
  'PositionNFT',
];

function extractAbi(contractName) {
  const artifactPath = join(FORGE_OUT, `${contractName}.sol`, `${contractName}.json`);
  if (!existsSync(artifactPath)) {
    console.warn(`Warning: ${artifactPath} not found. Run 'forge build' first.`);
    return null;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  return artifact.abi;
}

function main() {
  mkdirSync(ABIS_OUT, { recursive: true });

  const exports = [];

  for (const name of CONTRACTS) {
    const abi = extractAbi(name);
    if (!abi) continue;

    const filename = `${name}.abi.ts`;
    const content = `// Auto-generated by gen:abis — do not edit manually\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;

    writeFileSync(join(ABIS_OUT, filename), content);
    exports.push({ name, filename });
    console.log(`✓ Wrote ${name}.abi.ts`);
  }

  // Update index.ts
  const indexContent =
    exports
      .map(
        ({ name, filename }) =>
          `export { ${name}Abi } from './${filename.replace('.ts', '')}';`,
      )
      .join('\n') + '\n';

  writeFileSync(join(ABIS_OUT, 'index.ts'), indexContent);
  console.log(`✓ Updated abis/index.ts`);
}

main();
